apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-1
  clusterName: zookeeper-cluster-1
  labels:
    app: zookeeper-cluster-service-1
spec:
  clusterIP: 172.17.100.1
  selector:
    app: zookeeper-cluster-1
  ports:
    - port: 2181
      targetPort: 2181
      protocol: TCP
      name: client
    - port: 2888
      targetPort: 2888
      protocol: TCP
      name: follower
    - port: 3888
      targetPort: 3888
      protocol: TCP
      name: leader
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-2
  clusterName: zookeeper-cluster-2
  labels:
    app: zookeeper-cluster-service-2
spec:
  clusterIP: 172.17.100.2
  selector:
    app: zookeeper-cluster-2
  ports:
    - port: 2181
      protocol: TCP
      name: client
      targetPort: 2181
    - port: 2888
      protocol: TCP
      name: follower
      targetPort: 2888
    - port: 3888
      protocol: TCP
      name: leader
      targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster-3
  clusterName: zookeeper-cluster-3
  labels:
    app: zookeeper-cluster-service-3
spec:
  clusterIP: 172.17.100.3
  selector:
    app: zookeeper-cluster-3
  ports:
    - port: 2181
      protocol: TCP
      name: client
      targetPort: 2181
    - port: 2888
      protocol: TCP
      name: follower
      targetPort: 2888
    - port: 3888
      protocol: TCP
      name: leader
      targetPort: 3888