apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-1
  labels:
    app: kafka-cluster-1
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-cluster-1
      labels:
        app: kafka-cluster-1
    spec:
      hostname: kafka-cluster-1
      containers:
        - name: kafka-cluster-1
          image: wurstmeister/kafka:2.12-2.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-cluster-1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-cluster-1:2181,zookeeper-cluster-2:2181,zookeeper-cluster-3:2181"
            - name: KAFKA_BROKER_ID
              value: "1"
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-cluster-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-2
  labels:
    app: kafka-cluster-2
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-cluster-2
      labels:
        app: kafka-cluster-2
    spec:
      hostname: kafka-cluster-2
      containers:
        - name: kafka-cluster-2
          image: wurstmeister/kafka:2.12-2.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-cluster-2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-cluster-1:2181,zookeeper-cluster-2:2181,zookeeper-cluster-3:2181"
            - name: KAFKA_BROKER_ID
              value: "2"
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-cluster-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster-3
  labels:
    app: kafka-cluster-3
spec:
  replicas: 1
  template:
    metadata:
      name: kafka-cluster-3
      labels:
        app: kafka-cluster-3
    spec:
      hostname: kafka-cluster-3
      containers:
        - name: kafka-cluster-3
          image: wurstmeister/kafka:2.12-2.2.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: "kafka-cluster-3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-cluster-1:2181,zookeeper-cluster-2:2181,zookeeper-cluster-3:2181"
            - name: KAFKA_BROKER_ID
              value: "3"
      restartPolicy: Always
  selector:
    matchLabels:
      app: kafka-cluster-3