apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-1
spec:
  selector:
    app: kafka-cluster-1
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
  clusterIP: 172.17.100.11
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-2
spec:
  selector:
    app: kafka-cluster-2
  ports:
    - port: 9092
      targetPort: 9092
  type: ClusterIP
  clusterIP: 172.17.100.12
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster-3
spec:
  selector:
    app: kafka-cluster-3
  ports:
    - port: 9092
  type: ClusterIP
  clusterIP: 172.17.100.13
